name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["type:bug", "state:triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: A clear and concise description of what you expected to happen
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: A clear and concise description of what actually happened
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: Where did this bug occur?
      options:
        - Local development (Docker)
        - Vercel preview deployment
        - Production (chanoyu.ito.com)
        - Not sure
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Which part of the application is affected?
      options:
        - Authentication/Login
        - Object management (tea utensils)
        - Chakai (tea gatherings)
        - Image upload/storage
        - Database/Supabase
        - UI/Frontend
        - API routes
        - Data ingestion scripts
        - Other
    validations:
      required: true

  - type: textarea
    id: browser
    attributes:
      label: Browser & Version
      description: Which browser and version are you using?
      placeholder: e.g., Chrome 121.0.6167.85, Safari 17.2, Firefox 122.0
    validations:
      required: false

  - type: textarea
    id: console-errors
    attributes:
      label: Console Errors
      description: Any errors shown in the browser console or server logs
      placeholder: Paste any error messages here...
      render: text
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem
      placeholder: Drag and drop images here or paste image URLs
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: |
        - Does this happen consistently or intermittently?
        - Any recent changes that might be related?
        - Workarounds you've found?
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues to make sure this isn't a duplicate
          required: true
        - label: I have provided clear steps to reproduce the issue
          required: true
        - label: I have tested this on the latest version
          required: false