name: Preview (Vercel CLI)

on:
  push:
    branches: [dev]

concurrency:
  group: vercel-preview-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      VERCEL_CLI_TELEMETRY_DISABLED: 1
      NODE_ENV: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Verify Vercel token and scope
        run: npx vercel whoami --token "$VERCEL_TOKEN" --scope "$VERCEL_ORG_ID"

      - name: Pull Vercel env (preview)
        run: npx vercel pull --yes --environment=preview --token "$VERCEL_TOKEN" --scope "$VERCEL_ORG_ID"

      - name: Build locally with Vercel
        run: npx vercel build --yes

      # Optional: Deploy the prebuilt output as a preview deployment via CLI
      # If you already use Vercel Git integration to auto-deploy, you can remove this step.
      # - name: Deploy prebuilt output (preview)
      #   run: npx vercel deploy --prebuilt --yes --token "$VERCEL_TOKEN" --scope "$VERCEL_ORG_ID"


